pipeline {
    agent any

    tools {
        maven 'Maven 3.8.4'
    }

    stages {
        stage('build') {
            steps {
                echo 'compliling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }

            }
        }
        stage('test') {
            steps {
                echo 'Running Unit tests on worker app'

            }
        }
        stage('package') {
            steps {
                echo 'packing worker app'

            }
        }
    }
    post {
        always {
            echo 'Build pipeline for worker is complete'
        }
    }
}
